FROM jetbrains/teamcity-agent

USER root
RUN apt update && apt install -y golang-1.13 libpcap-dev wget flex bison byacc make wget libc6-armel-cross \
libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential libssl-dev bc \
gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

WORKDIR /tmp
RUN wget http://www.tcpdump.org/release/libpcap-1.8.1.tar.gz
RUN tar zxvf libpcap-1.8.1.tar.gz

WORKDIR libpcap-1.8.1
RUN env CC=arm-linux-gnueabi-gcc ./configure --host=arm-linux --with-pcap=linux; make

USER buildagent
WORKDIR /